version: "2.1"
services:
  womginx:
    build: .
    container_name: womginx
    environment:
      - PORT=80
      - SAFE_BROWSING=1
    ports:
      - '80:8080'
      - '443:8443'
    restart: unless-stopped
